In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [ ]:
df.isnull().values.any()

False

In [ ]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,53.303157,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,6.760171,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,30.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,48.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,54.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,58.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,65.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df = pd.read_csv('cardio_train.csv', sep=';')
# Conversion de la edad en días a años y redondear a enteros
df['age'] = (df['age'] / 365.25).round().astype(int)

In [ ]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,52,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,48,1,156,56.0,100,60,1,1,0,0,0,0

In [ ]:
#Características y variable objetivo
features = df.drop(columns=['id', 'cardio'])
target = df['cardio']

In [ ]:
#Escalador
scaler = MinMaxScaler()

In [ ]:
# Ajuste y transformacion de las características
normalized_features = scaler.fit_transform(features)

In [ ]:
normalized_data = pd.DataFrame(normalized_features, columns=features.columns)

In [ ]:
normalized_data['cardio'] = target.values

In [ ]:
print(normalized_data.head())

        age  gender    height    weight     ap_hi     ap_lo  cholesterol  \
0  0.571429     1.0  0.579487  0.273684  0.016079  0.013550          0.0
1  0.714286     0.0  0.517949  0.394737  0.017934  0.014453          1.0
2  0.628571     0.0  0.564103  0.284211  0.017316  0.012647          1.0
3  0.514286     1.0  0.584615  0.378947  0.018553  0.015357          0.0
4  0.514286     0.0  0.517949  0.242105  0.015461  0.011743          0.0

   gluc  smoke  alco  active  cardio
0   0.0    0.0   0.0     1.0       0
1   0.0    0.0   0.0     1.0       1
2   0.0    0.0   0.0     0.0       1
3   0.0    0.0   0.0     1.0       1
4   0.0    0.0   0.0     0.0       0